name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install modules
        run: yarn
      - name: Set up environment variable
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "::set-env name=AZURE_DEVOPS_PAT::${{ secrets.AZURE_DEVOPS_PAT }}"
      - name: Set up environment variable
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          export AZURE_DEVOPS_PAT="${{ secrets.AZURE_DEVOPS_PAT }}"
      - name: Run tests
        run: yarn test
